version: "3.1"

services:
  mysql-db:
    container_name: mysql-db
    image: mysql 
    restart: always
    env_file: .env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"

networks:
  default:
    external:
      name: localhost-net 