version: "3.1"
services:
    mysql-db:
        container_name: mysql-db
        restart: always
        image: mysql 
        env_file: .env
        ports:
            - "13306:3306"
        volumes:
            - ./data:/var/lib/mysql
        
