version: "3.1"

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    env_file: .env
    volumes:
        - ./data:/var/lib/postgresql/data
    ports:
        - "15432:5432"

networks:
  default:
    external:
      name: localhost-net 